### ISSUE TITLE
Can't ride pigs/horses on 1.8.x

### ISSUE THREAD

**Issue by Neeonn** [Matsv/ViaBackwards#49] opened 2018-06-22 22:41 UTC
### What is the output url of /viaversion dump?
> Can't even do that...
![image](https://user-images.githubusercontent.com/24417584/41801937-d53ab3ae-767d-11e8-97ba-018e609182b9.png)

### How/when does this error happen? login?:
> This happens when players try to ride tamed pigs/horses. It doesn't let players move/jump with them. This happens on 1.8.x version.

### Is there an error in the console? Use pastebin.com. Is there a kick message?:
> Nope. Nothing. Emptiness. Silence. Complete void.

If you need anything more, I can send it. Just please, fix this for me. Using latest versions of paperspigot (git-Paper-1452 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)), viaversion (1.3.0-DEV), viabackwards (2.3.2) and viarewind (1.3.10)

**Comment by Gerrygames** [comment] 2018-06-23 06:18
This is a know ViaRewind issue and there won‘t be a fix for it in the near future. The issue is caused by Mojang changing the vehicle movement being controlled by the server to being controlled by the client in 1.9. This can not be fixed on a protocol level. The only way I see would be to modify the spigot/nms code.

**Comment by Neeonn** [comment] 2018-06-23 10:34
Can I do something about this so this gets fixed?

sub, 23. jun 2018. 08.18 Gerrygames <notifications@github.com> је
написао/ла:

**Comment by Gerrygames** [comment] 2018-06-24 11:08
You can modify your server yourself.

**Closed** 2018-07-15 10:51 UTC
