### ISSUE TITLE
1.10 clients using Forge crash if an iron_nugget is dropped / on the ground

### ISSUE THREAD

**Issue by ProgrammerDan** [Matsv/ViaBackwards#17] opened 2017-07-10 15:26 UTC
### What is the output url of /viaversion dump?
> https://gist.github.com/e8ae100e151a829c1f2101cc29489d7b

### How/when does this error happen? login?:
> As described, Forge crashes if an iron_nugget is dropped. Crafting works fine and in inventory works fine, but any 1.10 Forge clients connected to a 1.12 server where someone crafts and drops an iron nugget will immediately be disconnected.

### Is there an error in the console? Use pastebin.com. Is there a kick message?:
> https://pastebin.com/3RXAqEDQ

Thanks!

**Comment by ProgrammerDan** [comment] 2017-07-10 15:27
Note that error is clientside. There is no error serverside. Most likely there needs to be a simple translation of item type sent to clients.

**Comment by Matsv** [comment] 2017-07-10 15:40
Will look into it when I have more free time. Thanks for reporting (:

**Comment by ProgrammerDan** [comment] 2017-07-10 15:45
<3 Thank you!

**Comment by Matsv** [comment] 2017-07-29 12:07
I'm unable to reproduce this. Does this happen on a Spigot 1.10 server without ViaVersion & ViaBackwards?

**Comment by ProgrammerDan** [comment] 2017-07-29 13:07
No. Spigot 1.12, with latest ViaVersion and ViaBackwards as of time of report.

Client connects with Forge 1.10.2, iron nugget held in inventory is fine -- as soon as it is dropped, crash occurs.

**Comment by Matsv** [comment] 2017-07-29 15:54
Could you give me your crashlog? (:

**Comment by ProgrammerDan** [comment] 2017-07-29 21:28
It was included in the OP.

Note, Spigot does not crash. The clients crash. It is being used offensively during PvP to "crash" the other players, then kill their combat loggers.

**Comment by Matsv** [comment] 2017-07-30 10:18
Found the bug. Should be fixed in the [latest devbuild](https://ci.viaversion.com/view/ViaBackwards/job/ViaBackwards-DEV/).
Please ask for a reopen if it still happens (:

**Closed by Matsv** 2017-07-30 10:18 UTC
