### ISSUE TITLE
Internal Exception: io.netty.handler.codec.EncoderException: java.lang.NullPointerException

### ISSUE THREAD

**Issue by Feerko** [Matsv/ViaBackwards#16] opened 2017-07-07 21:12 UTC
hello

### What is the output url of /viaversion dump?
>  https://gist.github.com/822ca0fb04e3681275288423819e08aa

### How/when does this error happen? login?:
> on join on version 1.9

### Is there an error in the console? Use pastebin.com. Is there a kick message?:
> [21:35:31 INFO]: Feerko lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.NullPointerException

it's caused by citizens. when i delete this plugin everythink works fine but i can't delete this plugin. it's very important for me.

**Comment by sebastianbinder** [comment] 2017-07-08 19:36
I can second this (at least the error). I have Citizens on my server as well but I haven't tried it without yet.

**Comment by Matsv** [comment] 2017-07-08 19:39
Duplicate of #11
Fixed in the latest devbuild (https://ci.viaversion.com/view/ViaBackwards/job/ViaBackwards-DEV/)

**Closed by Matsv** 2017-07-08 19:39 UTC
