### ISSUE TITLE
Bungeecord Join and Switch Console Errror

### ISSUE THREAD

**Issue by YugieDev** [Matsv/ViaBackwards#19] opened 2017-07-27 03:57 UTC
### What is the output url of /viaversion dump?
https://gist.github.com/anonymous/806ba5d1241ebf6d416d02734297c8d6

### How/when does this error happen? login?:
When a player logs in or switches server

### Is there an error in the console? Use pastebin.com. Is there a kick message?:
https://hastebin.com/putibubege.lua

**Comment by Matsv** [comment] 2017-07-27 08:22
Duplicate of #11
Fixed in the latest devbuild (https://ci.viaversion.com/view/ViaBackwards/job/ViaBackwards-DEV/)

**Closed by Matsv** 2017-07-27 08:22 UTC
