### ISSUE TITLE
Timeout from older versions on 1.12.2 server

### ISSUE THREAD

**Issue by mibby** [Matsv/ViaBackwards#31] opened 2017-09-20 04:13 UTC
ViaVersion dev 183
https://ci.viaversion.com/job/ViaVersion/183/
ViaBackwards dev 22
https://ci.viaversion.com/view/ViaBackwards/job/ViaBackwards/22/
Waterfall dev 144 (Upstream merged with BungeeCord dev 1266)
https://ci.destroystokyo.com/view/All/job/Waterfall/144/
Paper dev 1209 (Spigot 1.12.2)

BungeeCord proxy is updated to 1.12.2.
All servers are updated to 1.12.2.

@MylesIsCool @Matsv 

Players on all versions of 1.12 are able to connect to the server fine on the first connection of theirs. However players on earlier minecraft versions (1.12/1.12.1), as soon as they disconnect, they are not able to reconnect whatsoever. Upon trying to reconnect to the server, they get a 'Disconnected' message sent to their client - the proxy / server console states the connection 'Timed out'. Even users whose first connection to the server is on 1.12.2, if they disconnect and attempt to reconnect on an earlier version (i.e. 1.12.1), they are not able to connect. 

**_Only clients on 1.12.2 are able reconnect fine after an initial connection has been made._**

Players on 1.12.2 are able to disconnect and reconnect fine. Thus I have reason to believe the KeepAliveTracker for backwards compatibility may be the problem.

The KeepAlive class was updated in BungeeCord for the 1.12.2 update.
https://github.com/SpigotMC/BungeeCord/commit/0eaabdf5ca6dddd2bcdd57b77d3d02bc4967105e#diff-970a44e4ef1be42baed31a58b7b78ed0R16

I'm assuming here is where it is force terminating the client connection on reconnect when on older versions.
https://github.com/Matsv/ViaBackwards/commit/30f339400e1796ca46c0f760f8462ca8160910fe#diff-3dc077710b9aa885436ad11ff4317056R50

Config. 
http://paste.ubuntu.com/25577442/

Would it be possible to get a quick hot-fix for this problem? As players on older versions are not able to connect again after an initial connection had been made.

**Comment by MylesIsCool** [comment] 2017-09-20 07:36
This is most likely down to the bug in Spigot and you should update to the latest 1.12.2 build of spigot/paper etc.

**Comment by braceyourself07** [comment] 2017-09-20 13:02
I am having the same issue, using latest build of paperspigot (1209) and waterfall (144).  Ended up just reverting back to 1.12.1 for now.

**Comment by MylesIsCool** [comment] 2017-09-20 13:19
The new dev build should fix this, it's down to the client sending keep-alive randomly while loading the world - https://ci.viaversion.com/job/ViaBackwards/

(Also if @mibby doesn't already, update to latest spigot as there's bugs with async packet handling)

**Comment by mibby** [comment] 2017-09-20 15:35
I am already on the latest version of spigot (Paper fork), but thanks anyways. :) Appreciate the fix.

**Comment by mibby** [comment] 2017-09-20 20:39
@MylesIsCool This still seems to be an issue. Logging out and back in with 1.12.1 still disconnects users with a timed out on 1.12.2 server / proxy.

**Comment by MylesIsCool** [comment] 2017-09-20 21:35
Could you explain how to replicate this step by step?

**Comment by mibby** [comment] 2017-09-20 22:22
* Start 1.12.2 server.
* Start 1.12.2 proxy.
* User on 1.12.1 connects to the proxy.
* User is able to connect fine as all first connections made seem to go through.
* User disconnects.
* User tries to reconnect, but is unable to. Gets a 'disconnected' message on their client while the proxy / server console states the connection timed out.

**Comment by mibby** [comment] 2017-09-21 13:28
Testing myself to confirm, my first connection to the server since it restarted did not go through (client on 1.12.1, server on 1.12.2). It was timed out with the client being sent a disconnected message like before. Every consecutive connection after, I was able to connect fine. 

The server restarted since my last connection through automated restarts, but the proxy did not - it stays up through individual server restarts.

Restarting the server again to confirm, my first connection went through fine and I am able to relog multiple times without issue. However someone else was timed out on the restart when they reconnected. Other staff members have informed me that it still occurs when connecting on older versions as well, but it seems to be less consistent and more random now - assuming due to the KeepAlive packet comparison.

**Comment by MylesIsCool** [comment] 2017-09-21 17:18
I'm unable to replicate this with a 1.12.2 server with ViaBackwards using 1.12.1.

As per the latest update, we disregard any incorrect keep-alive. If you're able to modify ViaBackwards and put useful Logger info it would be appreciated. It's always possible that you have a plugin that causes this.

There may be some delay in fixing this issue, given that nobody else is having this issue I suspect it might be something in your configuration that others may not have and that I'm away for a few days.

If you're unable to resolve from testing a clean setup to see if it still happens please post the output of "/viaversion dump" so we have more info.

**Comment by braceyourself07** [comment] 2017-09-21 17:30
As I stated earlier in this post, I'm also having the issue, however I haven't had time yet to troubleshoot.  But according to logs I was getting the same messages as mibby. Clients logging in with 1.12.1 and getting Disconnected and Timed out quit messages and <handleDisconnection() called twice> in server logs.

**Comment by braceyourself07** [comment] 2017-09-22 12:46
I updated last night and so far no issues.  So it seems that the last ViaBackwards build has fixed the issue, at least for me.  I am also running build 1210 of paperspigot which just came out.  Not sure if that had any effect as well.

**Comment by Shevchik** [comment] 2017-09-22 13:44
You are still casting long to int and compare it on receive. If long doesn't fit into it you will never pass a packet to the server, which will result in timeout after 30 seconds.

**Comment by mibby** [comment] 2017-09-26 08:55
Bump. ^^

**Comment by MylesIsCool** [comment] 2017-09-26 13:15
In regards to what @Shevchik said, as long as casting is consistent we will always send the correct long. (From my knowledge the casting of a long should never differ, although there's small chance it could be something like 0 but viaversion would send the correct keep alive regardless)

This above wouldn't be related to this as the reported issue happens on reconnecting and not otherwise.

Would you be able to provide the output of "/viaversion dump" on servers running ViaVersion?

If you're able to replicate this is an isolated network, could you turn on debug=true in server.properties and provide the server log from a client login that gets disconnected?

**Comment by Matsv** [comment] 2017-10-26 12:56
Does this issue still happen using the latest devbuild? https://ci.viaversion.com/view/ViaBackwards/job/ViaBackwards/

**Comment by Matsv** [comment] 2017-11-06 19:15
Closing because nobody responded. If anyone is having this issue and able to reproduce it, ask for a reopen! (:

**Closed by Matsv** 2017-11-06 19:15 UTC
